## Numpy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones(())

array(1.)

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand()

0.6126909559288742

In [15]:
np.random.rand(5)

array([0.69493255, 0.44217783, 0.90010381, 0.38358438, 0.85941861])

In [16]:
np.random.randn(2)

array([ 0.20244271, -0.29549691])

In [17]:
np.random.randn(2,2)
#2 dimensional 

array([[-0.71528806,  0.06279255],
       [ 1.63511219, -0.9996189 ]])

In [18]:
np.random.randint(1,100)
#1 can be selected but 100 not

85

In [19]:
np.random.randint(1,100,10)

array([13, 95,  4, 95, 30, 91, 64, 93, 48, 39])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0,50,10)

In [23]:
ranarr

array([22, 19,  8, 17, 31,  2,  6, 33, 36, 31])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr.min()

2

In [26]:
ranarr.max()

36

In [27]:
ranarr.argmax()
#index of max value

8

In [28]:
ranarr.argmin()
#index of min value

5

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.dtype

dtype('int32')

In [31]:
from numpy.random import randint

In [32]:
randint(2,10)

4

## Numpy Indexing and Selection

In [33]:
import numpy as np

In [34]:
arr = np.arange(0,11)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

8

In [37]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [38]:
arr[:6] 
#index 6

array([0, 1, 2, 3, 4, 5])

In [39]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[0:5] = 100

In [41]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [42]:
arr = np.arange(0,11)
#reset the array

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
slice_of_arr = arr[0:6]

In [45]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [46]:
slice_of_arr[:] = 99
### !!!! ###
#not just changing slice_of_arr also the arr itself wow

In [47]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [48]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr_copy = arr.copy()

In [50]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [51]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
arr_copy [:] = 100
#arr will not be effected

In [53]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
############ 

In [56]:
import numpy as np

In [57]:
arr_2d = np.array ([[5,10,15],[20,25,30],[35,40,45]])

In [58]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
arr_2d[0]

array([ 5, 10, 15])

In [60]:
arr_2d[1][1]

25

In [61]:
arr_2d[2][1]

40

In [62]:
arr_2d[2,1]

40

In [63]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [64]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [65]:
arr = np.arange(1,11)

In [66]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
bool_arr = arr > 5

In [68]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [69]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [70]:
arr[arr<3]

array([1, 2])

In [71]:
arr_2d = np.arange(50).reshape(5,10)

In [72]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [73]:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [75]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [76]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Numpy Operations
 Array with Array
 
 Array with Scalars
 
 Universal Array Functions


In [77]:
import numpy as np

In [78]:
arr = np.arange(0,11)

In [79]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [87]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [88]:
arr / arr
#give nan if you do 0/0

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [89]:
1 / arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [90]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [91]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [93]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [94]:
np.max(arr)

10

In [95]:
arr.max()

10

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [97]:
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])